# Generated by Django 4.2.15 on 2025-09-07 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import puzzles.models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0005_auto_20220903_1806"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answersubmission",
            options={"verbose_name": "정답 제출", "verbose_name_plural": "정답 제출"},
        ),
        migrations.AlterModelOptions(
            name="erratum",
            options={"verbose_name": "정오표", "verbose_name_plural": "정오표"},
        ),
        migrations.AlterModelOptions(
            name="extraguessgrant",
            options={
                "verbose_name": "추가 시도 횟수 부여",
                "verbose_name_plural": "추가 시도 횟수 부여",
            },
        ),
        migrations.AlterModelOptions(
            name="hint", options={"verbose_name": "힌트", "verbose_name_plural": "힌트"},
        ),
        migrations.AlterModelOptions(
            name="puzzle", options={"verbose_name": "퍼즐", "verbose_name_plural": "퍼즐"},
        ),
        migrations.AlterModelOptions(
            name="puzzlemessage",
            options={"verbose_name": "퍼즐 메시지", "verbose_name_plural": "퍼즐 메시지"},
        ),
        migrations.AlterModelOptions(
            name="puzzleunlock",
            options={"verbose_name": "퍼즐 잠금 해제", "verbose_name_plural": "퍼즐 잠금 해제"},
        ),
        migrations.AlterModelOptions(
            name="round", options={"verbose_name": "라운드", "verbose_name_plural": "라운드"},
        ),
        migrations.AlterModelOptions(
            name="survey",
            options={"verbose_name": "설문조사", "verbose_name_plural": "설문조사"},
        ),
        migrations.AlterModelOptions(
            name="team", options={"verbose_name": "팀", "verbose_name_plural": "팀"},
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={"verbose_name": "팀원", "verbose_name_plural": "팀원"},
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="is_correct",
            field=models.BooleanField(verbose_name="정답 여부"),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.puzzle",
                verbose_name="퍼즐",
            ),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="submitted_answer",
            field=models.CharField(max_length=255, verbose_name="제출한 정답"),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="submitted_datetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="제출 일시"),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.team",
                verbose_name="팀",
            ),
        ),
        migrations.AlterField(
            model_name="answersubmission",
            name="used_free_answer",
            field=models.BooleanField(verbose_name="정답 보기 사용"),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="published",
            field=models.BooleanField(default=False, verbose_name="게시됨"),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="puzzle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.puzzle",
                verbose_name="퍼즐",
            ),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="puzzle_text",
            field=models.TextField(
                blank=True,
                help_text='\n        Text to show on the puzzle page. If blank, it will not appear there.\n        The text will be prefixed with "On (date)," when displayed, so you\n        should capitalize it the way it would appear mid-sentence. HTML is ok.\n    ',
                verbose_name="퍼즐 텍스트",
            ),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="타임스탬프"
            ),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="updates_text",
            field=models.TextField(
                blank=True,
                help_text='\n        Text to show on the Updates (errata) page. If blank, it will not appear there.\n        Use $PUZZLE to refer to the puzzle. The text will be prefixed with "On\n        (date)," when displayed, so you should capitalize it the way it would\n        appear mid-sentence. HTML is ok.\n    ',
                verbose_name="업데이트 텍스트",
            ),
        ),
        migrations.AlterField(
            model_name="extraguessgrant",
            name="extra_guesses",
            field=models.IntegerField(verbose_name="추가 시도 횟수"),
        ),
        migrations.AlterField(
            model_name="extraguessgrant",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.puzzle",
                verbose_name="퍼즐",
            ),
        ),
        migrations.AlterField(
            model_name="extraguessgrant",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.team",
                verbose_name="팀",
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="answered_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="답변 일시"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="claimed_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="담당 시작 일시"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="claimer",
            field=models.CharField(blank=True, max_length=255, verbose_name="담당자"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="discord_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="디스코드 ID"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="hint_question",
            field=models.TextField(verbose_name="힌트 질문"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="is_followup",
            field=models.BooleanField(default=False, verbose_name="추가 질문 여부"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="notify_emails",
            field=models.CharField(
                default="none", max_length=255, verbose_name="알림 이메일"
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.puzzle",
                verbose_name="퍼즐",
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="response",
            field=models.TextField(blank=True, verbose_name="응답"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="status",
            field=models.CharField(
                choices=[
                    ("NR", "응답 없음"),
                    ("ANS", "답변 완료"),
                    ("REF", "환불됨"),
                    ("OBS", "오래된 요청"),
                ],
                default="NR",
                max_length=3,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="submitted_datetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="제출 일시"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.team",
                verbose_name="팀",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="answer",
            field=models.CharField(
                help_text="정답 (정규화되지 않아도 됨)", max_length=255, verbose_name="정답"
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="body_template",
            field=models.CharField(
                blank=True,
                help_text='File name of a Django template (including .html) under\n        puzzle_bodies and solution_bodies containing the puzzle and\n        solution content, respectively. Defaults to slug + ".html" if not\n        specified.',
                max_length=255,
                verbose_name="본문 템플릿",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="emoji",
            field=models.CharField(
                default=":question:",
                help_text="이 퍼즐과 관련된 디스코드 연동에 사용할 이모지",
                max_length=32,
                verbose_name="이모지",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="is_meta",
            field=models.BooleanField(default=False, verbose_name="메타 퍼즐 여부"),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="name",
            field=models.CharField(max_length=255, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="order",
            field=models.IntegerField(default=0, verbose_name="순서"),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.round",
                verbose_name="라운드",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="slug",
            field=models.SlugField(
                help_text="URL에서 이 퍼즐을 식별하는 데 사용되는 slug (고유해야 함)",
                max_length=255,
                unique=True,
                verbose_name="슬러그",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="unlock_global",
            field=models.IntegerField(
                default=-1,
                help_text="0 이상일 경우, 라운드에 상관없이 메인 라운드 퍼즐이 N개 풀리면 잠금 해제됩니다.",
                verbose_name="전체 풀이 수 잠금 해제",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="unlock_hours",
            field=models.IntegerField(
                default=-1,
                help_text="0 이상일 경우, 퍼즐은 헌트 시작 N시간 후에 잠금 해제됩니다.",
                verbose_name="시간제 잠금 해제",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="unlock_local",
            field=models.IntegerField(
                default=-1,
                help_text="0 이상일 경우, 현재 라운드에서 메인 라운드 퍼즐이 N개 풀리면 잠금 해제됩니다.",
                verbose_name="라운드 내 풀이 수 잠금 해제",
            ),
        ),
        migrations.AlterField(
            model_name="puzzlemessage",
            name="guess",
            field=models.CharField(max_length=255, verbose_name="제출"),
        ),
        migrations.AlterField(
            model_name="puzzlemessage",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.puzzle",
                verbose_name="퍼즐",
            ),
        ),
        migrations.AlterField(
            model_name="puzzlemessage",
            name="response",
            field=models.TextField(verbose_name="응답"),
        ),
        migrations.AlterField(
            model_name="puzzleunlock",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.puzzle",
                verbose_name="퍼즐",
            ),
        ),
        migrations.AlterField(
            model_name="puzzleunlock",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.team",
                verbose_name="팀",
            ),
        ),
        migrations.AlterField(
            model_name="puzzleunlock",
            name="unlock_datetime",
            field=models.DateTimeField(verbose_name="잠금 해제 일시"),
        ),
        migrations.AlterField(
            model_name="puzzleunlock",
            name="view_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="열람 일시"),
        ),
        migrations.AlterField(
            model_name="round",
            name="meta",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_meta": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="puzzles.puzzle",
                verbose_name="메타",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="name",
            field=models.CharField(max_length=255, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="round",
            name="order",
            field=models.IntegerField(default=0, verbose_name="순서"),
        ),
        migrations.AlterField(
            model_name="round",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="슬러그"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="comments",
            field=models.TextField(blank=True, verbose_name="기타:"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="difficulty",
            field=puzzles.models.RatingField(adjective="난이도", max_rating=6),
        ),
        migrations.AlterField(
            model_name="survey",
            name="fun",
            field=puzzles.models.RatingField(adjective="재미", max_rating=6),
        ),
        migrations.AlterField(
            model_name="survey",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.puzzle",
                verbose_name="퍼즐",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="submitted_datetime",
            field=models.DateTimeField(auto_now=True, verbose_name="제출 일시"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.team",
                verbose_name="팀",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="allow_time_unlocks",
            field=models.BooleanField(
                default=True,
                help_text="Whether this team receives time-unlocked puzzles. Note that\n        if disabled, they may be able to access more puzzles by logging out",
                verbose_name="시간제 잠금 해제 허용",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
        ),
        migrations.AlterField(
            model_name="team",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="팀이 숨겨진 경우, 공개적으로 표시되지 않습니다.",
                verbose_name="숨김 여부",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="is_prerelease_testsolver",
            field=models.BooleanField(
                default=False,
                help_text="Whether this team is a prerelease testsolver. If true, the\n        team will have access to puzzles before the hunt starts",
                verbose_name="사전 테스트 팀 여부",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="last_solve_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="마지막 풀이 시각"),
        ),
        migrations.AlterField(
            model_name="team",
            name="start_offset",
            field=models.DurationField(
                default=datetime.timedelta,
                help_text="How much earlier this team should start, for early-testing\n        teams; be careful with this!",
                verbose_name="시작 시간 오프셋",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(
                help_text="점수판 및 공지에 사용될 공개 팀명",
                max_length=255,
                unique=True,
                verbose_name="팀명",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="total_free_answers_awarded",
            field=models.IntegerField(
                default=0,
                help_text="Number of additional free answers to award the team (on\n        top of the default amount per day)",
                verbose_name="총 부여된 정답 보기 수",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="total_hints_awarded",
            field=models.IntegerField(
                default=0,
                help_text="Number of additional hints to award the team (on top of\n        the default amount per day)",
                verbose_name="총 부여된 힌트 수",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="이메일 (선택)"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="name",
            field=models.CharField(max_length=255, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.team",
                verbose_name="팀",
            ),
        ),
    ]
