# Generated by Django 4.2.15 on 2025-09-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0007_auto_20250910_1634"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answersubmission",
            options={"verbose_name": "답안 제출", "verbose_name_plural": "답안 제출"},
        ),
        migrations.AlterModelOptions(
            name="puzzleunlock",
            options={"verbose_name": "퍼즐 해금", "verbose_name_plural": "퍼즐 해금"},
        ),
        migrations.AlterModelOptions(
            name="team", options={"verbose_name": "팀", "verbose_name_plural": "팀 목록"},
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={"verbose_name": "팀원", "verbose_name_plural": "팀원 목록"},
        ),
        migrations.AddField(
            model_name="team",
            name="team_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text='The time this team clicked the "Start Hunt" button.',
                null=True,
                verbose_name="Hunt Start Time",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="slug",
            field=models.SlugField(
                help_text="URL에서 이 퍼즐을 식별하는 데 사용되는 slug (고유해야 함)",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="unlock_global",
            field=models.IntegerField(
                default=-1,
                help_text="0 이상일 경우, 라운드에 상관없이 메인 라운드 퍼즐이 N개 풀리면 잠금 해제됩니다.",
                verbose_name="해금(전체해결)",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="unlock_hours",
            field=models.IntegerField(
                default=-1,
                help_text="0 이상일 경우, 퍼즐은 헌트 시작 N시간 후에 잠금 해제됩니다.",
                verbose_name="해금(시간)",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="unlock_local",
            field=models.IntegerField(
                default=-1,
                help_text="0 이상일 경우, 현재 라운드에서 메인 라운드 퍼즐이 N개 풀리면 잠금 해제됩니다.",
                verbose_name="해금(라운드해결)",
            ),
        ),
        migrations.AlterField(
            model_name="puzzleunlock",
            name="unlock_datetime",
            field=models.DateTimeField(verbose_name="해금 일시"),
        ),
        migrations.AlterField(
            model_name="round",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="team",
            name="allow_time_unlocks",
            field=models.BooleanField(
                default=True,
                help_text="Whether this team receives time-unlocked puzzles. Note that\n        if disabled, they may be able to access more puzzles by logging out",
                verbose_name="시간에 따른 해금 허용",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(
                help_text="점수판 및 공지에 사용될 공개 팀명",
                max_length=255,
                unique=True,
                verbose_name="팀 아이디",
            ),
        ),
        migrations.CreateModel(
            name="CannedHint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hint_id", models.CharField(max_length=255, verbose_name="Hint ID")),
                (
                    "opened_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="opened datetime"
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puzzles.puzzle",
                        verbose_name="퍼즐",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puzzles.team",
                        verbose_name="팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "canned hint unlock",
                "verbose_name_plural": "canned hint unlocks",
                "unique_together": {("team", "puzzle", "hint_id")},
            },
        ),
    ]
